
/*
 * CardReader.java
 *
 * Created on Feb 22, 2013, 9:33:21 PM
 */

package cardreader.ui;

import cardreader.datahandling.EventTypes;
import cardreader.datahandling.ReaderKeyListener;
import commonutilities.swing.ComponentPosition;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author javarobots <javarobots74@gmail.com>
 */
public class CardReader extends javax.swing.JFrame implements Observer {

    private static Controller mController;

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Model model = new Model();
                mController = new Controller(model);
                CardReader reader = new CardReader(model);
                model.addObserver(reader);
                model.notifyObservers();
                ComponentPosition.centerFrame(reader);
                reader.setVisible(true);
            }
        });
    }

    /** Creates new form CardReader */
    public CardReader() {
        initComponents();

    }

    /** Creates new form CardReader */
    public CardReader(Model model) {
        initComponents();
        mTextField.addKeyListener(new ReaderKeyListener(mController));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mTextField = new javax.swing.JTextField();
        mStatusTextLabel = new javax.swing.JLabel();
        mCardNumberLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mGreetingLabel = new javax.swing.JLabel();
        mNameLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mMenuBar = new javax.swing.JMenuBar();
        mFileMenu = new javax.swing.JMenu();
        mClearAttendanceMenuItem = new javax.swing.JMenuItem();
        mSaveAsMenuItem = new javax.swing.JMenuItem();
        mSetDataLocationMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        mReportMenu = new javax.swing.JMenu();
        mPtMenuItem = new javax.swing.JMenuItem();
        mLlabMenuItem = new javax.swing.JMenuItem();
        mAs100MenuItem = new javax.swing.JMenuItem();
        mAs200MenuItem = new javax.swing.JMenuItem();
        mAs300MenuItem = new javax.swing.JMenuItem();
        mAs400MenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DET 014 Attendance");
        setResizable(false);

        mStatusTextLabel.setText("Waiting");

        mCardNumberLabel.setText("Card Number:");

        mGreetingLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mGreetingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mGreetingLabel.setText("Greeting");

        mNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mNameLabel.setText("Name");

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mFileMenu.setText("File");

        mClearAttendanceMenuItem.setText("Clear Attendance");
        mClearAttendanceMenuItem.setToolTipText("Clear the existing data file.");
        mClearAttendanceMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mClearAttendanceMenuItemActionPerformed(evt);
            }
        });
        mFileMenu.add(mClearAttendanceMenuItem);

        mSaveAsMenuItem.setText("Save As...");
        mSaveAsMenuItem.setToolTipText("Save the data file to a specified location.");
        mSaveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSaveAsMenuItemActionPerformed(evt);
            }
        });
        mFileMenu.add(mSaveAsMenuItem);

        mSetDataLocationMenuItem.setText("Set Data Location...");
        mSetDataLocationMenuItem.setToolTipText("Set the directory for data files.");
        mSetDataLocationMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSetDataLocationMenuItemActionPerformed(evt);
            }
        });
        mFileMenu.add(mSetDataLocationMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.setToolTipText("Exit the application.");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        mFileMenu.add(exitMenuItem);

        mMenuBar.add(mFileMenu);

        mReportMenu.setText("Reports");

        mPtMenuItem.setText("PT");
        mPtMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPtMenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mPtMenuItem);

        mLlabMenuItem.setText("LLAB");
        mLlabMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLlabMenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mLlabMenuItem);

        mAs100MenuItem.setText("AS 100");
        mAs100MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAs100MenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mAs100MenuItem);

        mAs200MenuItem.setText("AS 200");
        mAs200MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAs200MenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mAs200MenuItem);

        mAs300MenuItem.setText("AS 300");
        mAs300MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAs300MenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mAs300MenuItem);

        mAs400MenuItem.setText("AS 400");
        mAs400MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAs400MenuItemActionPerformed(evt);
            }
        });
        mReportMenu.add(mAs400MenuItem);

        mMenuBar.add(mReportMenu);

        setJMenuBar(mMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mGreetingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mCardNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mStatusTextLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(mNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mStatusTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mCardNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mGreetingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mClearAttendanceMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mClearAttendanceMenuItemActionPerformed
        mController.clearAttendance();
    }//GEN-LAST:event_mClearAttendanceMenuItemActionPerformed

    private void mSetDataLocationMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSetDataLocationMenuItemActionPerformed
        mController.setFileLocation();
    }//GEN-LAST:event_mSetDataLocationMenuItemActionPerformed

    private void mSaveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSaveAsMenuItemActionPerformed
        mController.fileSaveAs();
    }//GEN-LAST:event_mSaveAsMenuItemActionPerformed

    private void mPtMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPtMenuItemActionPerformed
        mController.runReport(EventTypes.PT);
    }//GEN-LAST:event_mPtMenuItemActionPerformed

    private void mLlabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLlabMenuItemActionPerformed
        mController.runReport(EventTypes.LLAB);
    }//GEN-LAST:event_mLlabMenuItemActionPerformed

    private void mAs100MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAs100MenuItemActionPerformed
        mController.runReport(EventTypes.AS100);
    }//GEN-LAST:event_mAs100MenuItemActionPerformed

    private void mAs200MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAs200MenuItemActionPerformed
        mController.runReport(EventTypes.AS200);
    }//GEN-LAST:event_mAs200MenuItemActionPerformed

    private void mAs300MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAs300MenuItemActionPerformed
        mController.runReport(EventTypes.AS300);
    }//GEN-LAST:event_mAs300MenuItemActionPerformed

    private void mAs400MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAs400MenuItemActionPerformed
        mController.runReport(EventTypes.AS400);
    }//GEN-LAST:event_mAs400MenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuItem mAs100MenuItem;
    private javax.swing.JMenuItem mAs200MenuItem;
    private javax.swing.JMenuItem mAs300MenuItem;
    private javax.swing.JMenuItem mAs400MenuItem;
    private javax.swing.JLabel mCardNumberLabel;
    private javax.swing.JMenuItem mClearAttendanceMenuItem;
    private javax.swing.JMenu mFileMenu;
    private javax.swing.JLabel mGreetingLabel;
    private javax.swing.JMenuItem mLlabMenuItem;
    private javax.swing.JMenuBar mMenuBar;
    private javax.swing.JLabel mNameLabel;
    private javax.swing.JMenuItem mPtMenuItem;
    private javax.swing.JMenu mReportMenu;
    private javax.swing.JMenuItem mSaveAsMenuItem;
    private javax.swing.JMenuItem mSetDataLocationMenuItem;
    private javax.swing.JLabel mStatusTextLabel;
    private javax.swing.JTextField mTextField;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof Model){
            Model m = (Model)o;
            mStatusTextLabel.setText(m.getStatusText());
            mTextField.setEnabled(m.isEnableDataTextField());
            mGreetingLabel.setText(m.getGreeting());
            mNameLabel.setText(m.getName());
            if (m.isClearData()){
                mTextField.setText("");
            }
        }
    }

}
